### PR TITLE
Fix bugs

### LINKED ISSUE #89: In the list of promotions per room missing the link to go back
Create the link Back

### PR DESCRIPTION
**Pull request by paulotijero**
Resolve #89 #97 #94 #90 #100 #101 #98

### CODE REVIEW

File: app/controllers/admin/promotions_controller.rb [hunk 1]
```diff
@@ -1,5 +1,6 @@
 class Admin::PromotionsController < ApplicationController
-  before_action :set_promotion, only: [:index, :new, :show, :edit, :create, :update]
+  before_action :set_hotel, only: [:index, :new, :show, :edit, :create, :update]
+  before_action :set_promotion, only: [:show, :edit, :update, :destroy]
```
Comment (liannivin) [inline app/controllers/admin/promotions_controller.rb]: You forgot ':index' for set_promotion.

Comment (paulotijero) [reply app/controllers/admin/promotions_controller.rb]: You're right
